### ISSUE TITLE
missing header <util/Log.h>

### ISSUE THREAD

**Issue by dunn** [greebles/greebles-desktop#71]
Trying to compile on macOS 10.12.6 the build failed with
```
[  0%] Building CXX object CMakeFiles/custom.dir/Users/alex/clones/greebles-desktop/src/shared/src/common/ControlSet.cpp.o
/Users/alex/clones/greebles-desktop/src/shared/src/common/ControlSet.cpp:5:10: fatal error: 'util/Log.h' file not found
#include <util/Log.h>
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/custom.dir/Users/alex/clones/greebles-desktop/src/shared/src/common/ControlSet.cpp.o] Error 1
make[1]: *** [CMakeFiles/custom.dir/all] Error 2
make: *** [all] Error 2
```
I see that header is included in a number of places but it's not local to the codebase and I couldn't find any clue as to whence it's supposed to be provided.

**Comment by lrenaud** [comment]
https://github.com/drautb/SOAR is the repo. You'll need to do some cleanup of the build directories to get things moving again.
